import copy, json
from pathlib import Path

ROOT = Path('/home/ubuntu/mandarim-em-rede-conteudo')
PDF = ROOT/'content/pdf_first'
COLECAO = 'Coleção 01 · Primeiras interações'
SEQ = ['situar','observar','reconhecer','ler','recuperar','escrever','reorganizar','recombinar','produzir','revisar']
PKG = {'essencial':['W1','W2','V1','R1','R2','R3','R4'], 'extensoes':{'pronuncia':True,'escrita':True,'caracteres':True,'contraste':True,'vocabulario':True,'quiz':False,'anotacoes':True,'consolidacao':False}}

def st(funcao, mandarim, pinyin, sentido, tipo='base', **extra):
    x={'funcao':funcao,'mandarim':mandarim,'pinyin':pinyin,'sentido_funcional':sentido,'tipo':tipo}
    x.update(extra); return x

def make(code, title, func, result, situation, emotion, difficulty, prep, structures, keywords, decision, blocks, expected, reconstructions, bank, molds, scenarios, artifact, criteria, next_topic, module):
    keywords=[{'hanzi':h,'pinyin':p,'sentido':s,'categoria':c,'uso':u} for _label,h,p,s,c,u in keywords]
    unit={
      'schema_version':'2.0','produto':'Mandarim em Rede','unidade':{
        'content_profile':'pdf-first-rich-v2','codigo':code,'titulo':title,'colecao':COLECAO,'nivel':'iniciante','status':'draft',
        'objetivo_comunicativo':func,'resultado_minimo':result,'situacao_principal':situation,'contexto_emocional':emotion,'dificuldade_principal':difficulty,
        'preparacao':prep,'estruturas':structures,
        'mapa_decisao':[{'intencao':a,'mandarim':b,'pinyin':c} for a,b,c in decision],
        'hanzi_alvo':[], 'palavras_chave':keywords,
        'atividades':{
          'reconhecimento':[{'situacao':f'Escolha a forma adequada para: {a}','opcao_a':b,'opcao_b':decision[(i+1)%len(decision)][1],'resposta':'a'} for i,(a,b,c) in enumerate(decision[:4])],
          'reorganizacao':{'instrucao':'Ordene os blocos para formar a expressão indicada.','blocos':blocks,'resultado_esperado':expected,'reconstrucoes':[{'pedido':p,'mandarim':m} for p,m in reconstructions]},
          'recombinacao':{'instrucao':'Mantenha a estrutura e troque somente o elemento indicado.','banco':[{'rotulo':r,'hanzi':h,'pinyin':p} for r,h,p in bank],'moldes':molds}
        },
        'producao':{'cenarios':[{'titulo':a,'instrucao':b,'apoio':c,'campos':d} for a,b,c,d in scenarios]},
        'artefato_pratico':artifact,'criterios_autoavaliacao':criteria,'sequencia':SEQ,'pacotes':PKG,'proxima_unidade_sugerida':next_topic
      }
    }
    # Use complete words/characters from the unit as hanzi targets; prioritize first six lexical items.
    seen=[]
    for item in keywords:
        if item['hanzi'] not in seen:
            seen.append(item['hanzi'])
    unit['unidade']['hanzi_alvo']=[{'hanzi':h,'pinyin':next(x['pinyin'] for x in keywords if x['hanzi']==h),'sentido':next(x['sentido'] for x in keywords if x['hanzi']==h),'prioridade':'alta' if i<3 else 'media'} for i,h in enumerate(seen[:8])]
    return unit

units={}
# B04: possession, migrated from the repository's existing B04 reference.
units['B04']=make('B04','Posse e especificação','Perguntar e responder de quem é um objeto usando 我的、你的 e 的.','Produzir quatro trocas curtas sobre posse, substituindo o possuidor e o objeto sem consultar o mapa completo.','Em uma sala ou reunião, distinguir objetos e pessoas e dizer a quem cada item pertence.','O aluno quer identificar o dono de um objeto sem parecer invasivo ou hesitante.','Manter a ordem possuidor + 的 + objeto e distinguir 我的 de 你的.',['Observe o objeto.','Decida quem é o possuidor.','Tente perguntar antes de consultar.'],[
 st('identificar objeto próprio','这是我的书。','Zhè shì wǒ de shū.','Este é o meu livro.'),st('identificar objeto do interlocutor','那是你的书。','Nà shì nǐ de shū.','Aquele é o seu livro.'),st('perguntar de quem é','谁的书？','Shéi de shū?','Livro de quem?','particula',particula='谁的'),st('identificar objeto de professor','这是老师的书。','Zhè shì lǎoshī de shū.','Este é o livro da professora.'),st('responder posse própria','这是我的。','Zhè shì wǒ de.','Este é o meu.'),st('especificar pessoa','我的朋友','Wǒ de péngyou','Meu amigo ou minha amiga.','substituivel',slot='pessoa')],
 [('meu','我的','wǒ de','meu/minha','informacao','uso do possuidor'),('seu','你的','nǐ de','seu/sua','informacao','posse do interlocutor'),('livro','书','shū','livro','objeto','objeto identificado'),('professor','老师','lǎoshī','professor ou professora','pessoa','possuidor'),('amigo','朋友','péngyou','amigo ou amiga','pessoa','pessoa especificada'),('quem','谁','shéi','quem','informacao','pergunta'),('isto','这','zhè','isto/este','informacao','referente próximo'),('aquilo','那','nà','aquilo/aquele','informacao','referente distante')],
 [('Perguntar posse','谁的书？','Shéi de shū?'),('Responder posse própria','这是我的。','Zhè shì wǒ de.'),('Especificar possuidor','这是老师的书。','Zhè shì lǎoshī de shū.'),('Trocar objeto','那是你的书。','Nà shì nǐ de shū.')],['谁','的','书','？'],'谁的书？',[('Este é o meu livro。','这是我的书。'),('Aquele é o seu livro。','那是你的书。')],[('objeto','书','shū'),('pessoa','朋友','péngyou'),('pessoa','老师','lǎoshī')],['这是我的…。','那是你的…。','谁的…？'],[('Mesa compartilhada','Identifique três objetos e diga de quem são.','com_apoio',['objeto','possuidor']),('Pergunta de posse','Pergunte e responda sobre dois objetos sem o mapa.','menos_apoio',['pergunta','resposta'])],'Inventário de três objetos com dono, pergunta e resposta.',['Uso 我的 para mim.','Uso 你的 para o interlocutor.','Coloco 的 entre possuidor e objeto.','Troco o objeto mantendo a estrutura.'],'Números e informações pessoais','Entrada na interação')
# B05
units['B05']=make('B05','Números e informações pessoais','Perguntar e informar idade, telefone ou número em uma interação inicial.','Produzir três trocas com números, usando 几 ou 多少 conforme a informação solicitada.','Em uma apresentação ou cadastro simples, pedir e fornecer uma informação numérica.','O aluno quer informar seus dados sem travar ao ouvir uma pergunta curta.','Distinguir 几 de 多少 e manter o número na posição correta.',['Observe qual informação é numérica.','Escolha pergunta curta ou específica.','Fale o número antes de conferir.'],[
 st('perguntar idade','你几岁？','Nǐ jǐ suì?','Quantos anos você tem?','operador'),st('informar idade','我二十岁。','Wǒ èrshí suì.','Eu tenho vinte anos.'),st('perguntar número','你的电话号码是多少？','Nǐ de diànhuà hàomǎ shì duōshao?','Qual é o seu número de telefone?','operador'),st('informar número','我的电话号码是八八八八。','Wǒ de diànhuà hàomǎ shì bā bā bā bā.','Meu número é 8888.'),st('perguntar quantidade aberta','有多少人？','Yǒu duōshao rén?','Quantas pessoas há?','operador'),st('responder quantidade','有三个人。','Yǒu sān ge rén.','Há três pessoas.')] if False else [
 st('perguntar idade','你几岁？','Nǐ jǐ suì?','Quantos anos você tem?','operador'),st('informar idade','我二十岁。','Wǒ èrshí suì.','Eu tenho vinte anos.'),st('perguntar número','你的电话号码是多少？','Nǐ de diànhuà hàomǎ shì duōshao?','Qual é o seu número de telefone?','operador'),st('informar número','我的电话号码是八八八八。','Wǒ de diànhuà hàomǎ shì bā bā bā bā.','Meu número é 8888.'),st('perguntar quantidade aberta','有多少人？','Yǒu duōshao rén?','Quantas pessoas há?','operador'),st('responder quantidade','有三个人。','Yǒu sān ge rén.','Há três pessoas.')],
 [('idade','几岁','jǐ suì','quantos anos','informacao','idade'),('vinte','二十','èrshí','vinte','quantidade','número'),('telefone','电话','diànhuà','telefone','objeto','contato'),('número','号码','hàomǎ','número','informacao','dado'),('quanto','多少','duōshao','quanto/quantos','quantidade','quantidade aberta'),('três','三','sān','três','quantidade','número'),('pessoa','人','rén','pessoa','pessoa','contagem'),('ter','有','yǒu','haver/ter','acao','existência')],
 [('Perguntar idade','你几岁？','Nǐ jǐ suì?'),('Responder idade','我二十岁。','Wǒ èrshí suì.'),('Perguntar número','你的电话号码是多少？','Nǐ de diànhuà hàomǎ shì duōshao?'),('Responder quantidade','有三个人。','Yǒu sān ge rén.')],['你','几','岁','？'],'你几岁？',[('Tenho vinte anos。','我二十岁。'),('Há três pessoas。','有三个人。')],[('idade','二十','èrshí'),('quantidade','三','sān'),('dado','八八八八','bā bā bā bā')],['你…岁？','我的…是…','有多少…？'],[('Cadastro','Pergunte e registre idade e telefone de uma pessoa.','com_apoio',['idade','telefone']),('Apresentação','Dê duas informações numéricas sem olhar.','sem_apoio',['idade','número'])],'Ficha curta de informações pessoais numéricas.',['Escolho 几 para idade.','Uso 多少 para quantidade aberta.','Produzo números com ritmo estável.','Respondo sem inverter a ordem.'],'Horários e agenda','Situações práticas')
# B06
units['B06']=make('B06','Horários e agenda','Perguntar e informar horário ou momento de uma atividade cotidiana.','Produzir três perguntas e respostas sobre horário usando 现在, 点 e 分.','Combinar uma aula ou encontro perguntando quando começa e respondendo com um horário.','O aluno quer marcar algo sem medo de não entender o horário.','Distinguir agora, hora e minuto e manter o classificador temporal na sequência.',['Imagine o compromisso.','Ouça o número antes da unidade de tempo.','Tente perguntar e responder em voz alta.'],[
 st('perguntar a hora','现在几点？','Xiànzài jǐ diǎn?','Que horas são agora?','operador'),st('informar hora','现在三点。','Xiànzài sān diǎn.','Agora são três horas.'),st('perguntar início','几点开始？','Jǐ diǎn kāishǐ?','A que horas começa?','operador'),st('informar início','三点半开始。','Sān diǎn bàn kāishǐ.','Começa às três e meia.'),st('perguntar momento','什么时候？','Shénme shíhou?','Quando?','operador'),st('responder momento','下午三点。','Xiàwǔ sān diǎn.','Às três da tarde.')],
 [('agora','现在','xiànzài','agora','informacao','tempo atual'),('hora','点','diǎn','hora em ponto','quantidade','unidade de hora'),('meia','半','bàn','meia','quantidade','meia hora'),('começar','开始','kāishǐ','começar','acao','início'),('quando','什么时候','shénme shíhou','quando','informacao','momento'),('tarde','下午','xiàwǔ','tarde','informacao','período'),('três','三','sān','três','quantidade','número'),('três','三','sān','três','quantidade','número')],
 [('Perguntar hora','现在几点？','Xiànzài jǐ diǎn?'),('Informar hora','现在三点。','Xiànzài sān diǎn.'),('Perguntar início','几点开始？','Jǐ diǎn kāishǐ?'),('Responder momento','下午三点。','Xiàwǔ sān diǎn.')],['现在','几','点','？'],'现在几点？',[('Começa às três e meia。','三点半开始。'),('Às três da tarde。','下午三点。')],[('hora','三点','sān diǎn'),('momento','下午','xiàwǔ'),('meia','半','bàn')],['现在…点？','…点开始。','下午…点。'],[('Agenda','Pergunte e registre dois horários.','com_apoio',['pergunta','resposta']),('Marcação','Combine um encontro usando um horário novo.','menos_apoio',['horário','atividade'])],'Cartão de agenda com duas atividades e horários.',['Uso 点 depois do número.','Reconheço 半 como meia hora.','Pergunto quando com 什么时候.','Respondo com período e horário.'],'Localização e direções','Situações práticas')
# B07
units['B07']=make('B07','Localização e direções','Perguntar onde está uma pessoa ou objeto e responder com uma localização simples.','Realizar quatro trocas de localização usando 在, 这里, 那里 e um lugar conhecido.','Em um prédio novo, descobrir onde estão uma pessoa, uma sala ou um objeto.','O aluno precisa se orientar e sente urgência para obter uma resposta curta.','Distinguir pergunta de localização e resposta com 在.',['Observe o mapa do lugar.','Escolha pessoa, objeto ou sala.','Produza a pergunta antes de olhar a resposta.'],[
 st('perguntar onde','在哪里？','Zài nǎlǐ?','Onde está?','operador'),st('responder aqui','在这里。','Zài zhèlǐ.','Está aqui.'),st('responder ali','在那里。','Zài nàlǐ.','Está ali.'),st('localizar pessoa','老师在教室。','Lǎoshī zài jiàoshì.','A professora está na sala.'),st('localizar objeto','书在桌子上。','Shū zài zhuōzi shàng.','O livro está sobre a mesa.'),st('perguntar localização específica','你在哪儿？','Nǐ zài nǎr?','Onde você está?','operador')],
 [('onde','哪里','nǎlǐ','onde','lugar','pergunta'),('aqui','这里','zhèlǐ','aqui','lugar','perto'),('ali','那里','nàlǐ','ali','lugar','longe'),('sala','教室','jiàoshì','sala de aula','lugar','lugar'),('mesa','桌子','zhuōzi','mesa','objeto','referente'),('sobre','上','shàng','sobre/em cima','lugar','posição'),('professor','老师','lǎoshī','professor ou professora','pessoa','pessoa'),('estar','在','zài','estar em','acao','localização')],
 [('Perguntar localização','在哪里？','Zài nǎlǐ?'),('Responder aqui','在这里。','Zài zhèlǐ.'),('Localizar pessoa','老师在教室。','Lǎoshī zài jiàoshì.'),('Localizar objeto','书在桌子上。','Shū zài zhuōzi shàng.')],['在','哪','里','？'],'在哪里？',[('O livro está sobre a mesa。','书在桌子上。'),('A professora está na sala。','老师在教室。')],[('perto','这里','zhèlǐ'),('longe','那里','nàlǐ'),('lugar','教室','jiàoshì')],['…在哪里？','…在这里。','…在…。'],[('Mapa da sala','Pergunte onde estão dois itens.','com_apoio',['item','lugar']),('Busca','Dê duas localizações sem consultar.','sem_apoio',['pergunta','resposta'])],'Mapa simples com quatro referentes e suas localizações.',['Uso 在 para localizar.','Distingo 这里 e 那里.','Pergunto onde sem traduzir palavra por palavra.','Respondo com lugar compreensível.'],'Pedidos em café ou restaurante','Situações práticas')
# B08
units['B08']=make('B08','Pedidos em café ou restaurante','Fazer um pedido simples e responder confirmando item ou quantidade.','Realizar três pedidos curtos usando 请, 要 e uma forma de confirmação.','Em um café ou restaurante, pedir uma bebida ou item e confirmar o pedido.','O aluno quer ser compreendido sem precisar formular uma frase longa.','Distinguir 要 como intenção de pedir e 请 como marcador de cortesia.',['Visualize o cardápio.','Escolha item e quantidade.','Faça o pedido em voz alta.'],[
 st('pedir item','我要咖啡。','Wǒ yào kāfēi.','Eu quero café.','base'),st('pedir com cortesia','请给我茶。','Qǐng gěi wǒ chá.','Por favor, me dê chá.','base'),st('perguntar confirmação','要这个吗？','Yào zhège ma?','Quer este?','particula',particula='吗'),st('confirmar escolha','要这个。','Yào zhège.','Quero este.'),st('pedir quantidade','我要两个。','Wǒ yào liǎng ge.','Quero dois.'),st('agradecer','谢谢。','Xièxie.','Obrigado ou obrigada.','fixo')],
 [('querer','要','yào','querer/pedir','acao','intenção'),('café','咖啡','kāfēi','café','objeto','bebida'),('chá','茶','chá','chá','objeto','bebida'),('dar','给','gěi','dar','acao','pedido'),('este','这个','zhège','este item','objeto','escolha'),('dois','两个','liǎng ge','dois itens','quantidade','quantidade'),('por favor','请','qǐng','por favor','acao','cortesia'),('obrigado','谢谢','xièxie','obrigado/obrigada','acao','fechamento')],
 [('Pedir item','我要咖啡。','Wǒ yào kāfēi.'),('Pedir com cortesia','请给我茶。','Qǐng gěi wǒ chá.'),('Confirmar escolha','要这个。','Yào zhège.'),('Agradecer','谢谢。','Xièxie.')],['我','要','咖啡','。'],'我要咖啡。',[('Quero café。','我要咖啡。'),('Quero dois。','我要两个。')],[('bebida','咖啡','kāfēi'),('bebida','茶','chá'),('item','这个','zhège')],['我要…。','请给我…。','要…吗？'],[('Cardápio','Escolha dois itens e faça pedidos.','com_apoio',['item','quantidade']),('Pedido sem apoio','Faça um pedido e confirme a escolha.','menos_apoio',['pedido','confirmação'])],'Cardápio preenchido com três pedidos e quantidades.',['Uso 要 para pedir.','Uso 请 para cortesia.','Confirmo a escolha com este item.','Produzo o fechamento social.'],'Preferências e escolhas','Situações práticas')
# B09
units['B09']=make('B09','Preferências e escolhas','Dizer do que gosta, do que não gosta e escolher entre duas opções.','Expressar duas preferências e uma recusa usando 喜欢, 不喜欢 e 还是.','Em uma conversa sobre comida, bebida ou atividades, comparar opções e escolher.','O aluno quer expressar gosto pessoal sem parecer limitado a respostas decoradas.','Distinguir 喜欢 de 不喜欢 e manter a escolha clara.',['Escolha duas opções.','Decida preferência ou recusa.','Diga a escolha em voz alta.'],[
 st('dizer que gosta','我喜欢茶。','Wǒ xǐhuan chá.','Eu gosto de chá.'),st('dizer que não gosta','我不喜欢咖啡。','Wǒ bù xǐhuan kāfēi.','Eu não gosto de café.'),st('perguntar preferência','你喜欢什么？','Nǐ xǐhuan shénme?','Do que você gosta?','operador'),st('oferecer escolha','茶还是咖啡？','Chá háishì kāfēi?','Chá ou café?','operador'),st('escolher item','我喜欢茶。','Wǒ xǐhuan chá.','Eu prefiro chá.'),st('confirmar escolha','茶。','Chá.','Chá.','fixo')],
 [('gostar','喜欢','xǐhuan','gostar','acao','preferência'),('não','不','bù','não','informacao','negação'),('chá','茶','chá','chá','objeto','opção'),('café','咖啡','kāfēi','café','objeto','opção'),('o que','什么','shénme','o que','informacao','pergunta'),('ou','还是','háishì','ou','informacao','escolha'),('gosto','喜欢','xǐhuan','gostar','acao','preferência'),('eu','我','wǒ','eu','pessoa','sujeito')],
 [('Perguntar preferência','你喜欢什么？','Nǐ xǐhuan shénme?'),('Dizer gosto','我喜欢茶。','Wǒ xǐhuan chá.'),('Dizer recusa','我不喜欢咖啡。','Wǒ bù xǐhuan kāfēi.'),('Oferecer escolha','茶还是咖啡？','Chá háishì kāfēi?')],['茶','还是','咖啡','？'],'茶还是咖啡？',[('Eu gosto de chá。','我喜欢茶。'),('Eu não gosto de café。','我不喜欢咖啡。')],[('opção','茶','chá'),('opção','咖啡','kāfēi'),('opção','茶','chá')],['我喜欢…。','我不喜欢…。','…还是…？'],[('Preferências','Diga do que gosta e não gosta.','com_apoio',['gosto','recusa']),('Escolha','Escolha entre duas opções sem o mapa.','sem_apoio',['opção','preferência'])],'Cartão de preferências com três escolhas e justificativa curta.',['Digo gosto com 喜欢.','Formo a recusa com 不喜欢.','Entendo a escolha com 还是.','Mantenho a opção explícita.'],'Capacidade e pedidos de ajuda','Preferências e escolhas')
# B10
units['B10']=make('B10','Capacidade e pedidos de ajuda','Dizer que consegue ou não consegue fazer algo e pedir ajuda de forma simples.','Produzir três trocas usando 会 ou 能 e uma solicitação curta de ajuda.','Em uma aula ou tarefa nova, informar capacidade e pedir ajuda quando necessário.','O aluno quer participar mesmo quando não tem certeza de que consegue realizar a tarefa.','Distinguir 会 como habilidade aprendida e 能 como possibilidade na situação.',['Identifique a tarefa.','Decida habilidade ou possibilidade.','Peça ajuda sem abandonar a interação.'],[
 st('dizer que sabe fazer','我会说中文。','Wǒ huì shuō Zhōngwén.','Eu sei falar chinês.'),st('dizer que não consegue','我不会写。','Wǒ bú huì xiě.','Eu não sei escrever.'),st('perguntar capacidade','你会吗？','Nǐ huì ma?','Você sabe fazer?','particula',particula='吗'),st('dizer possibilidade','我能试试。','Wǒ néng shìshi.','Eu posso tentar.'),st('pedir ajuda','请帮我。','Qǐng bāng wǒ.','Por favor, me ajude.'),st('agradecer ajuda','谢谢你。','Xièxie nǐ.','Obrigado ou obrigada.')],
 [('saber fazer','会','huì','saber fazer','acao','habilidade'),('falar','说','shuō','falar','acao','tarefa'),('chinês','中文','Zhōngwén','chinês','informacao','idioma'),('escrever','写','xiě','escrever','acao','tarefa'),('poder','能','néng','poder/conseguir','acao','possibilidade'),('tentar','试试','shìshi','tentar','acao','estratégia'),('ajudar','帮','bāng','ajudar','acao','pedido'),('obrigado','谢谢','xièxie','obrigado','acao','fechamento')],
 [('Dizer habilidade','我会说中文。','Wǒ huì shuō Zhōngwén.'),('Dizer limite','我不会写。','Wǒ bú huì xiě.'),('Dizer possibilidade','我能试试。','Wǒ néng shìshi.'),('Pedir ajuda','请帮我。','Qǐng bāng wǒ.')],['我','会','说','中文','。'],'我会说中文。',[('Eu não sei escrever。','我不会写。'),('Por favor, me ajude。','请帮我。')],[('habilidade','说中文','shuō Zhōngwén'),('tarefa','写','xiě'),('estratégia','试试','shìshi')],['我会…。','我不会…。','请帮我…'],[('Sala de aula','Diga o que consegue fazer e peça ajuda.','com_apoio',['habilidade','pedido']),('Tarefa nova','Use 能 para dizer que pode tentar.','menos_apoio',['possibilidade','ação'])],'Cartão de habilidades e pedidos de ajuda.',['Distingo 会 e 能 no contexto.','Formo a negativa com 不会.','Peço ajuda com clareza.','Continuo a interação após uma dificuldade.'],'Rotina e atividades','Preferências e escolhas')
# B11
units['B11']=make('B11','Rotina e atividades','Dizer uma atividade cotidiana e perguntar o que alguém faz.','Produzir quatro frases sobre rotina usando 去, 看, 学 e uma atividade escolhida.','Em uma conversa curta sobre o dia, perguntar e responder sobre atividades comuns.','O aluno quer falar de si com frases curtas e reconhecíveis.','Manter o verbo antes do objeto e distinguir atividade de lugar.',['Escolha uma atividade do banco.','Organize pessoa + verbo + objeto.','Fale uma frase sem consultar.'],[
 st('dizer que vai estudar','我去学习。','Wǒ qù xuéxí.','Eu vou estudar.'),st('dizer que vai trabalhar','我去工作。','Wǒ qù gōngzuò.','Eu vou trabalhar.'),st('dizer que lê','我看书。','Wǒ kàn shū.','Eu leio.'),st('dizer que estuda chinês','我学中文。','Wǒ xué Zhōngwén.','Eu estudo chinês.'),st('perguntar atividade','你做什么？','Nǐ zuò shénme?','O que você faz?','operador'),st('responder atividade','我看电影。','Wǒ kàn diànyǐng.','Eu assisto a um filme.')],
 [('ir','去','qù','ir','acao','movimento'),('estudar','学习','xuéxí','estudar','acao','atividade'),('trabalhar','工作','gōngzuò','trabalhar','acao','atividade'),('ler','看书','kàn shū','ler','acao','atividade'),('aprender','学','xué','estudar/aprender','acao','atividade'),('chinês','中文','Zhōngwén','chinês','informacao','objeto de estudo'),('fazer','做','zuò','fazer','acao','pergunta'),('filme','电影','diànyǐng','filme','objeto','atividade')],
 [('Ir estudar','我去学习。','Wǒ qù xuéxí.'),('Ir trabalhar','我去工作。','Wǒ qù gōngzuò.'),('Ler','我看书。','Wǒ kàn shū.'),('Perguntar atividade','你做什么？','Nǐ zuò shénme?')],['我','去','学习','。'],'我去学习。',[('Eu vou trabalhar。','我去工作。'),('Eu estudo chinês。','我学中文。')],[('estudo','学习','xuéxí'),('trabalho','工作','gōngzuò'),('filme','电影','diànyǐng')],['我去…。','我看…。','你做…？'],[('Rotina','Monte três frases sobre seu dia.','com_apoio',['atividade','frase']),('Conversa','Pergunte e responda sobre duas atividades.','sem_apoio',['pergunta','resposta'])],'Miniagenda diária com três atividades em mandarim.',['Coloco o verbo antes do objeto.','Pergunto atividade com 做什么.','Produzo frases de rotina.','Recombino pelo menos três atividades.'],'Consolidação da entrada na interação','Preferências e escolhas')

for code, data in units.items():
    (PDF/f'{code}-{data["unidade"]["titulo"].lower().replace(" ","-").replace("/","")}.json').write_text(json.dumps(data, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')

# Rich batch B02-B11: B02/B03 existing plus generated B04-B11.
items=[]
for code in [f'B{i:02d}' for i in range(2,12)]:
    path=next(PDF.glob(f'{code}-*.json'))
    items.append({'id':code,'source':f'content/pdf_first/{path.name}','content_profile':'pdf-first-rich-v2','template_profile':'b-family-workbook-v1','material':'WORKBOOK DO ALUNO','edicao':'EDIÇÃO 01 · 2026'})
batch={'schema_version':'pdf-first-rich-batch-v2','produto':'Mandarim em Rede','content_profile':'pdf-first-rich-v2','template_registry':'templates/registry.json','output_label':'colecao-01-rich-10-topicos','colecao':COLECAO,'modulo':'Primeiras interações e situações práticas','expected_pages_policy':'range','min_pages':11,'max_pages':13,'units':items}
(PDF/'colecao_01_rich_10_topicos.json').write_text(json.dumps(batch, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
print(json.dumps({'units_created':list(units), 'batch_units':[x['id'] for x in items]}, ensure_ascii=False))
